### ISSUE TITLE
On Windows 10 in IE11 and Edge, only the footer is shown instead of the full page

### ISSUE THREAD

**Issue by EvanHahn** [fightforthefuture/earth-day-live-widget#15]
To quote [this issue comment][0]:

> 2\. On Windows 10 IE11 the full page is not rendered regardless of whether it's with or without the close button. When one tries to access the full page, the footer is shown instead.
> ...
> 4\. On Windows 10 Edge, similarly to IE11, the full page is not rendered, instead the footer is shown.

This should be fixed.

[0]: https://github.com/fightforthefuture/earth-day-live-widget/issues/9#issuecomment-608409675

**Comment by dtoakley** [comment]
I think this may have been caused by us using `new URLSearchParams` in demo.html, that broke the JS execution. I've refactored that to use vanilla js that is supported by IE/Edge. 

It would be good to retest this to confirm.

**Comment by EvanHahn** [comment]
This seems to be fixed—thanks!

Screenshot from IE11 as proof:

<img width="1834" alt="Screenshot from IE11" src="https://user-images.githubusercontent.com/777712/79003269-dcf92080-7b17-11ea-8ad4-a9cfcb209173.png">
